const Jokers = [
  { id: 1, name: "Guasón de Barrio", image: "joker1", effect: "context.multiplier += 4", price: 100 },
  { id: 2, name: "Tío Gilito", image: "joker2", effect: "if (cards.suit === 'oros') context.multiplier += 3", price: 120 },
  { id: 3, name: "Don Juan de la Baraja", image: "joker3", effect: "if (cards.suit === 'copas') context.multiplier += 3", price: 150 },
  { id: 4, name: "Espadachín Colérico", image: "joker4", effect: "if (cards.suit === 'espadas') context.multiplier += 3", price: 200 },
  { id: 5, name: "Tragaldabas de Bastos", image: "joker5", effect: "if (cards.suit === 'bastos') context.multiplier += 3", price: 180 },
  { id: 6, name: "Loco de Atar", image: "locoJoker", effect: "if (context.handType === 'Trío') context.multiplier += 12", price: 160 },
  { id: 7, name: "Chiflado de Pares", image: "chifladoJoker", effect: "if (context.handType === 'Doble Pareja') context.multiplier += 10", price: 250 },
  { id: 8, name: "Pirado de Escaleras", image: "piradoJoker", effect: "if (context.handType === 'Escalera') context.multiplier += 12", price: 220 },
  { id: 9, name: "Bufón de Colores", image: "bufonJoker", effect: "if (context.handType === 'Color') context.multiplier += 10", price: 100 },
  { id: 10, name: "Zorro de la Pareja", image: "zorroJoker", effect: "if (context.handType === 'Pareja') context.chips += 50", price: 120 },
  { id: 11, name: "Astuto del Trío", image: "astutoJoker", effect: "if (context.handType === 'Trío') context.chips += 100", price: 150 },
  { id: 12, name: "Listo de la Doble", image: "listoJoker", effect: "if (context.handType === 'Doble Pareja') context.chips += 80", price: 200 },
  { id: 13, name: "Tramposo de la Escalera", image: "tramposoJoker", effect: "if (context.handType === 'Escalera') context.chips += 100", price: 180 },
  { id: 14, name: "Marañoso del Color", image: "maranosoJoker", effect: "if (context.handType === 'Color') context.chips += 80", price: 160 },
  { id: 15, name: "Sombra del Guasón", image: "sombraJoker", effect: "context.multiplier += context.emptyJokerSlots", price: 250 },
  { id: 16, name: "El Banderín", image: "banderinJoker", effect: "context.chips += 30 * context.remainingDiscards", price: 220 },
  { id: 17, name: "Cima Mística", image: "cimaJoker", effect: "if (context.remainingDiscards === 0) context.multiplier += 15", price: 100 },
  { id: 18, name: "Guasón Abstracto", image: "abstractoJoker", effect: "context.multiplier += 3 * context.jokerCount", price: 120 },
  { id: 19, name: "Erudito", image: "eruditoJoker", effect: "if (card.rank === 'ace') { context.chips += 20; context.multiplier += 4; }", price: 150 },
  { id: 20, name: "Caminante", image: "caminanteJoker", effect: "card.permanentChipBonus = (card.permanentChipBonus || 0) + 5", price: 200 },
  { id: 21, name: "El Noble Cavendish", image: "nobleJoker", effect: "context.multiplier *= 3; if (Math.random() < 0.01) context.jokerDestroyed = true", price: 180 },
  { id: 22, name: "El Barón", image: "baronJoker", effect: "if (card.rank === 'rey') context.multiplier *= 1.5", price: 160 },
  { id: 23, name: "La Fotografía", image: "fotografiaJoker", effect: "if (!context.firstFigurePlayed) { context.multiplier *= 2; context.firstFigurePlayed = true; }", price: 250 },
  { id: 24, name: "El Juglar", image: "juglarJoker", effect: "if (card.rank === 'rey' || card.rank === 'caballo') context.multiplier *= 2", price: 220 },
  { id: 25, name: "El Ahorrador", image: "ahorradorJoker", effect: "context.multiplier += 2 * Math.floor(context.chips / 5)", price: 100 },
  { id: 26, name: "El Caballista", image: "caballistaJoker", effect: "if (card.rank === 'caballo') context.multiplier += 13", price: 120 },
  { id: 27, name: "El Acróbata", image: "acrobataJoker", effect: "context.chips += 250; context.handSize -= 2", price: 150 },
  { id: 28, name: "El Dúo", image: "duoJoker", effect: "if (context.handType === 'Pareja') context.multiplier *= 2", price: 200 },
  { id: 29, name: "El Trío", image: "trioJoker", effect: "if (context.handType === 'Trío') context.multiplier *= 3", price: 180 },
  { id: 30, name: "La Familia", image: "familiaJoker", effect: "if (context.handType === 'Póker') context.multiplier *= 4", price: 160 },
  { id: 31, name: "La Orden", image: "ordenJoker", effect: "if (context.handType === 'Escalera') context.multiplier *= 3", price: 250 },
  { id: 32, name: "La Tribu", image: "tribuJoker", effect: "if (context.handType === 'Color') context.multiplier *= 2", price: 220 },
  { id: 33, name: "Punta de Flecha", image: "flechaJoker", effect: "if (card.suit === 'espadas') context.chips += 50", price: 100 },
  { id: 34, name: "Gema en Bruto", image: "gemaJoker", effect: "if (card.suit === 'oros') context.chips += 1", price: 120 },
  { id: 35, name: "Guasón Manchado", image: "manchadoJoker", effect: "if (card.suit === 'copas') { card.suit = 'oros'; } else if (card.suit === 'bastos') { card.suit = 'espadas'; }", price: 150 },
  { id: 36, name: "El Trapecista", image: "trapecistaJoker", effect: "if (context.isFinalHand) context.multiplier *= 3", price: 200 },
  { id: 37, name: "El Billete Dorado", image: "billeteJoker", effect: "if (card.suit === 'oros') context.chips += 4", price: 180 },
  { id: 38, name: "La Cromos", image: "cromosJoker", effect: "context.multiplier += 1.5 * context.jokerCount", price: 160 },
  { id: 39, name: "El Guasón Dorado", image: "doradoJoker", effect: "context.chips += 4", price: 250 }
];

export default Jokers;